site_name: GestureMouseApp
site_url: https://github.com/Marc1T/gestureControl
site_description: Application de contrôle gestuelle pour interagir avec votre ordinateur
site_author: NANKOULI Marc Thierry

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair

repo_url: https://github.com/Marc1T/gestureControl
repo_name: GitHub

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            filters: ["!^_"]  # Exclure les membres privés
            show_root_heading: true
            show_source: true
  - git-revision-date

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.css
  - styles/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Accueil: index.md
  - Guide d'utilisation:
      - Guide complet: guide/user-guide.md
  - Développement:
      - Architecture et composants: implementation/system.md
      - API et modules: api/reference.md
  - À propos: about.md
